void C_Bubble();
void Calculate(int *arr, int N, int command, int type);
void Print(int *arr, int N);
void PrintColumn();
void C_Selection();
void C_Insertion();
void C_Merge();
void C_Quick1();
void C_Quick2();
void C_Quick3();